Repository WMass/nanoAOD-tools, pull requests merged in 2020-12, with the labels that each got.

#12 Clean jets form muons before Prefire weight is computed.
  python/postprocessing/modules/common/PrefireCorr.py
Labels: bugfix, enhancement

#7 features for condor to help resubmissions, also filtering input files
  python/postprocessing/modules/common/PrefireCorr.py
  python/postprocessing/wmass/postproc.py
Labels: enhancement

#11 changing a few things for gen-level stuff
  python/postprocessing/wmass/CSVariables.py
  python/postprocessing/wmass/Vproducer.py
  python/postprocessing/wmass/genLepSelection.py
  python/postprocessing/wmass/lheWeightsFlattener.py
Labels: bugfix, enhancement

#13 small fix to the skipFiles option in postproc.py
  python/postprocessing/wmass/postproc.py
Labels: bugfix

#14 make condor mode in postproc.py fully xrd dependent
  python/postprocessing/wmass/postproc.py
  scripts/checkZombies.py
Labels: enhancement
