Repository WMass/nanoAOD-tools, pull requests merged in 2020-11, with the labels that each got.

#4 Adding modules and some features in postproc.py
  interface/WeightCalculatorFromHistogram.h
  python/postprocessing/data/pileup/PileupData_2016Legacy_FpostHIPMandGH.root
  python/postprocessing/data/pileup/PileupData_2016Legacy_all2016.root
  python/postprocessing/data/pileup/PileupData_2016Legacy_upTo2016FwithHIPM.root
  python/postprocessing/data/pileup/PileupMC_2016Legacy.root
  python/postprocessing/helpers/jetReCleanerHelper.cc
  python/postprocessing/modules/common/puWeightProducer.py
  python/postprocessing/wmass/CSVariables.py
  python/postprocessing/wmass/Vproducer.py
  python/postprocessing/wmass/Wproducer.py
  python/postprocessing/wmass/genLepSelection.py
  python/postprocessing/wmass/jetReCleaner.py
  python/postprocessing/wmass/keep_and_drop_MC.txt
  python/postprocessing/wmass/keep_and_drop_TEST.txt
  python/postprocessing/wmass/postproc.py
  python/postprocessing/wmass/triggerMatchProducer.py
  src/WeightCalculatorFromHistogram.cc
Labels: enhancement

#5 merging gen-stuff into master
  python/postprocessing/wmass/CSVariables.py
  python/postprocessing/wmass/Vproducer.py
  python/postprocessing/wmass/Wproducer.py
  python/postprocessing/wmass/genLepSelection.py
  python/postprocessing/wmass/keep_and_drop_MC.txt
  python/postprocessing/wmass/postproc.py
Labels: bugfix, enhancement

#6 Proposal for cleaning up the post prcessing sequence building
  README.md
  python/postprocessing/wmass/SequenceBuilder.py
  python/postprocessing/wmass/keep_and_drop_Data.txt
  python/postprocessing/wmass/keep_and_drop_MC.txt
  python/postprocessing/wmass/postproc.py
  python/postprocessing/wmass/preSelection.py
  python/postprocessing/wmass/simpleEffPlotter.C
Labels: enhancement

#10 PR to fix the prefsr type leptons
  python/postprocessing/framework/postprocessor.py
  python/postprocessing/wmass/genLepSelection.py
  python/postprocessing/wmass/keep_and_drop_Data.txt
  python/postprocessing/wmass/keep_and_drop_MC.txt
Labels: bugfix

#8 Clean jets w.r.t muons before applying prefire map
  python/postprocessing/modules/common/PrefireCorr.py
Labels: bugfix

#9 Check the size of lepton vector before access.
  python/postprocessing/wmass/genLepSelection.py
Labels: bugfix
